#!/usr/bin/env bash
#
# sync.sh — Commit local changes and sync them to GitHub via a PR with squash auto-merge.
#
# Mirrors the sync flow used in ryans-claude-plugins, minus the plugin-specific
# build steps. main is PR-only by CONVENTION (see CONTRIBUTING.md) — not
# server-enforced on the free plan — so this never pushes straight to main: it
# always goes branch -> PR -> squash merge, then fast-forwards your local main to
# the merged commit. This is the maintainer/Claude helper; a plain-IDE developer
# just uses normal git + a PR on GitHub.
#
# Usage:
#   ./sync.sh                          # commit "Sync updates" + PR + auto-merge + ff local main
#   ./sync.sh "fix proxy CORS"         # commit with your message
#   ./sync.sh --no-push "wip"          # commit locally only, don't push / open a PR
#

set -e
cd "$(dirname "$0")"

# Tell the post-commit hook to stand down — sync.sh drives its own PR push and
# must not have its internal main-commit hijacked by a direct auto-push.
export SKIP_AUTO_PUSH=1

PUSH=true
MSG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-push) PUSH=false; shift ;;
    *)         MSG="$1"; shift ;;
  esac
done

if [ -z "$MSG" ]; then
  MSG="Sync updates"
fi

echo "=== sync.sh ==="
echo "  push to GitHub: $PUSH"
echo "  commit message: $MSG"
echo

# 1. Stage + check for changes
echo "=== Staging changes ==="
git add -A
CHANGED=$(git diff --cached --name-only | wc -l | tr -d ' ')
if [ "$CHANGED" = "0" ]; then
  echo "  Nothing to commit. Exiting."
  exit 0
fi
echo "  $CHANGED file(s) staged:"
git diff --cached --name-only | sed 's/^/    /'
echo

# 2. Commit
echo "=== Committing ==="
git commit -m "$MSG

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>"
echo

# 3. Push via PR (never direct to main — main is PR-only by convention)
if [ "$PUSH" = true ]; then
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
  if [ "$CURRENT_BRANCH" = "main" ]; then
    # We committed on main locally — move that commit to a feature branch and PR it.
    SLUG=$(echo "$MSG" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-//; s/-$//' | cut -c1-40)
    BRANCH="chore/sync-${SLUG}-$(date +%Y%m%d-%H%M%S)"
    echo "=== Moving local main commit to branch $BRANCH ==="
    git branch "$BRANCH"
    git fetch origin main --quiet || true
    git reset --hard origin/main
    git checkout "$BRANCH"
  else
    BRANCH="$CURRENT_BRANCH"
    echo "=== Already on branch $BRANCH — pushing as-is ==="
  fi

  echo "=== Pushing branch + opening PR + enabling squash auto-merge ==="
  git push -u origin "$BRANCH"
  gh pr create --title "$MSG" --body "$(cat <<EOF
## Summary
$MSG

Generated by sync.sh.

## Files updated
$(git diff --name-only origin/main..."$BRANCH" | sed 's/^/- /')
EOF
)"
  # --auto only works when there are required checks to wait for. If the repo
  # has no required checks, --auto fails with "Pull request is in clean status"
  # — fall back to an immediate squash merge in that case.
  gh pr merge --squash --auto --delete-branch || gh pr merge --squash --delete-branch

  # 4. Pull the merged squash commit back to local main so the working copy
  #    stays in sync with origin/main. Best-effort; failures just print a warning.
  echo
  echo "=== Syncing local main with the merged commit ==="
  CURRENT_AFTER_MERGE=$(git rev-parse --abbrev-ref HEAD)
  git checkout main 2>/dev/null || true
  if git pull --ff-only 2>&1; then
    echo "  ✓ local main fast-forwarded"
    # Clean up the local feature branch (remote was deleted by --delete-branch).
    if [ "$CURRENT_AFTER_MERGE" != "main" ] && git rev-parse --verify "$CURRENT_AFTER_MERGE" >/dev/null 2>&1; then
      git branch -D "$CURRENT_AFTER_MERGE" 2>/dev/null && echo "  ✓ deleted local branch $CURRENT_AFTER_MERGE"
    fi
  else
    echo "  ⚠️  Could not fast-forward local main (PR may still be merging, or remote diverged). Run \`git pull\` manually in a moment."
  fi

  echo
  echo "Done. PR opened with squash auto-merge enabled."
else
  echo "Skipped push (--no-push). Commit is local only."
fi
